// <auto-generated />
namespace KaraokeBar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeTabIdFromSongs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeTabIdFromSongs));
        
        string IMigrationMetadata.Id
        {
            get { return "201703231807285_removeTabIdFromSongs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
